### ISSUE TITLE
Failling to compile using NODE LTS Version (10.14.0)

### ISSUE THREAD

**Issue by gustavomassa** [RuntimeTools/appmetrics#560]
Hello,

Appmetrics 4.0.0.1 (last commit added support to Node 10 on windows) is failing to compile on windows:

System Windows_NT 10.0.17134
MSBuild 14.0
Node: 10.14.0
Node-Gyp 3.8.0

```
LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const std::basic_ostream<char,struct std::char_traits<char> >::`vftable'"
 (__imp_??_7?$basic_ostream@DU?$char_traits@D@std@@@std@@6B@)'; link without /DELAYLOAD:node.exe [C:\Projetos\Webbuffet\node_modules\appmetrics\build\omr-agentcore\memoryplugin.vcxpro
j]
c:\projetos\webbuffet\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' [C:\Projetos\Webbuffet\node_modules\appmetrics\build\nodeprofp
lugin.vcxproj]
```

**Comment by tobespc** [comment]
we've just released appmetrics 4.0.1 , can you retest please as this is compiling for us

**Comment by sjanuary** [comment]
@gustavomassa if you're installing from source you need to update the omr-agentcore submodule as we made changes there to fix this issue.  Maybe try a completely clean checkout or installing from npm?  I've just tried with 10.14.0 in case there was any difference to 10.13.0 and it works for me.

**Comment by DanailMinchev** [comment]
I have similar problem when using Docker `node:10-alpine` image:

Sorry for the long log file, but I am not sure which part can be useful for you:
```
Unsupported version v10.14.0. Trying rebuild.
Falling back to node-gyp rebuild
make: Entering directory '/tmp/node_modules/appmetrics-statsd/node_modules/appmetrics/build'
  ACTION binding_gyp_appmetrics_target_Set_appmetrics_reported_version_build_level Release/obj.target/appmetrics/geni/appmetrics.cpp
infile: ./src/appmetrics.cpp
outfile: /tmp/node_modules/appmetrics-statsd/node_modules/appmetrics/build/Release/obj.target/appmetrics/geni/appmetrics.cpp
Replacing '"99\.99\.99\.29991231"' with '"3.1.3.201811301732"'
  CXX(target) Release/obj.target/appmetrics/geni/appmetrics.o
In file included from ../../../../nan/nan_new.h:189:0,
                 from ../../../../nan/nan.h:222,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:22:
../../../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)':
../../../../nan/nan_implementation_12_inl.h:340:37: warning: 'static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:5053:37: note: declared here
                 static Local<Value> New(Local<String> value));
                                     ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from Release/obj.target/appmetrics/geni/appmetrics.cpp:22:0:
../../../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../../../nan/nan.h:1066:53: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
In file included from Release/obj.target/appmetrics/geni/appmetrics.cpp:22:0:
../../../../nan/nan.h:1080:74: warning: 'int v8::String::WriteUtf8(char*, int, int*, int) const' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:2659:21: note: declared here
                 int WriteUtf8(char* buffer, int length = -1,
                     ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/plugins/node/prof/watchdog.h:21:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:25:
../src/plugins/node/prof/compat-inl.h: In static member function 'static void compat::CpuProfiler::StartCpuProfiling(v8::Isolate*, v8::Local<v8::String>)':
../src/plugins/node/prof/compat-inl.h:302:34: warning: 'v8::CpuProfiler* v8::Isolate::GetCpuProfiler()' is deprecated: CpuProfiler should be created with CpuProfiler::New call. [-Wdeprecated-declarations]
   return isolate->GetCpuProfiler()->StartProfiling(title, record_samples);
                                  ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:7485:30: note: declared here
                 CpuProfiler* GetCpuProfiler());
                              ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/plugins/node/prof/watchdog.h:21:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:25:
../src/plugins/node/prof/compat-inl.h: In static member function 'static const v8::CpuProfile* compat::CpuProfiler::StopCpuProfiling(v8::Isolate*, v8::Local<v8::String>)':
../src/plugins/node/prof/compat-inl.h:312:34: warning: 'v8::CpuProfiler* v8::Isolate::GetCpuProfiler()' is deprecated: CpuProfiler should be created with CpuProfiler::New call. [-Wdeprecated-declarations]
   return isolate->GetCpuProfiler()->StopProfiling(title);
                                  ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:7485:30: note: declared here
                 CpuProfiler* GetCpuProfiler());
                              ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from Release/obj.target/appmetrics/geni/appmetrics.cpp:25:0:
../src/plugins/node/prof/watchdog.h: In function 'const char* watchdog::StartCpuProfiling(v8::Isolate*, uint64_t)':
../src/plugins/node/prof/watchdog.h:251:6: error: 'struct sigevent' has no member named '_sigev_un'; did you mean 'sigevent'?
   ev._sigev_un._tid = profiler_tid;
      ^~~~~~~~~
../src/plugins/node/prof/watchdog.h:252:21: error: 'SIGEV_THREAD_ID' was not declared in this scope
   ev.sigev_notify = SIGEV_THREAD_ID;
                     ^~~~~~~~~~~~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'std::__cxx11::string toStdString(v8::Local<v8::String>)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:90:21: warning: 'int v8::String::WriteUtf8(char*, int, int*, int) const' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
     s->WriteUtf8(buf);
                     ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:2659:21: note: declared here
                 int WriteUtf8(char* buffer, int length = -1,
                     ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'std::__cxx11::string* getModuleDir(v8::Local<v8::Object>)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:187:126: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     std::string moduleFilename(toStdString(module->Get(Nan::New<String>(asciiString("filename")).ToLocalChecked())->ToString()));
                                                                                                                              ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'v8::Local<v8::Object> getProcessObject()':
Release/obj.target/appmetrics/geni/appmetrics.cpp:192:121: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     return Nan::GetCurrentContext()->Global()->Get(Nan::New<String>(asciiString("process")).ToLocalChecked())->ToObject();
                                                                                                                         ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'std::__cxx11::string* findApplicationDir()':
Release/obj.target/appmetrics/geni/appmetrics.cpp:198:50: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         return getModuleDir(mainModule->ToObject());
                                                  ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE setOption(Nan::NAN_METHOD_ARGS_TYPE)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:333:43: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<String> value = info[0]->ToString();
                                           ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:334:46: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     Local<String> value1 = info[1]->ToString();
                                              ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE getOption(Nan::NAN_METHOD_ARGS_TYPE)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:344:43: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<String> value = info[0]->ToString();
                                           ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE spath(Nan::NAN_METHOD_ARGS_TYPE)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:383:43: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<String> value = info[0]->ToString();
                                           ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'void emitMessage(uv_async_t*, int)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:435:44: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
         listener->callback->Call(argc, argv);
                                            ^
In file included from Release/obj.target/appmetrics/geni/appmetrics.cpp:22:0:
../../../../nan/nan.h:1655:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE nativeEmit(Nan::NAN_METHOD_ARGS_TYPE)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:495:49: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         String::Utf8Value str(info[0]->ToString());
                                                 ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:495:50: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
         String::Utf8Value str(info[0]->ToString());
                                                  ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:505:49: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         String::Utf8Value str(info[1]->ToString());
                                                 ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:505:50: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
         String::Utf8Value str(info[1]->ToString());
                                                  ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE sendControlCommand(Nan::NAN_METHOD_ARGS_TYPE)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:531:54: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         String::Utf8Value topicArg(info[0]->ToString());
                                                      ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:531:55: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
         String::Utf8Value topicArg(info[0]->ToString());
                                                       ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:532:56: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         String::Utf8Value commandArg(info[1]->ToString());
                                                        ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:532:57: warning: 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)' is deprecated: Use Isolate version [-Wdeprecated-declarations]
         String::Utf8Value commandArg(info[1]->ToString());
                                                         ^
In file included from /root/.node-gyp/10.14.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.0/include/node/node.h:63,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'bool isGlobalAgent(v8::Local<v8::Object>)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:662:50: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> filename = parent->ToObject()->Get(Nan::New<String>(asciiString("filename")).ToLocalChecked());
                                                  ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:663:97: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (filename->IsString() && isAppMetricsFile("index.js", toStdString(filename->ToString()))) {
                                                                                                 ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:664:57: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             Local<Value> grandparent = parent->ToObject()->Get(Nan::New<String>(asciiString("parent")).ToLocalChecked());
                                                         ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:665:61: warning: 'v8::Local<v8::Object> v8::Value::ToObject() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             Local<Value> gpfilename = grandparent->ToObject()->Get(Nan::New<String>(asciiString("filename")).ToLocalChecked());
                                                             ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp:666:108: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             if (gpfilename->IsString() && isAppMetricsFile("launcher.js", toStdString(gpfilename->ToString()))) {
                                                                                                            ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
Release/obj.target/appmetrics/geni/appmetrics.cpp: In function 'bool isGlobalAgentAlreadyLoaded(v8::Local<v8::Object>)':
Release/obj.target/appmetrics/geni/appmetrics.cpp:684:98: warning: 'v8::Local<v8::String> v8::Value::ToString() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
             if (entry->IsString() && isAppMetricsFile("launcher.js", toStdString(entry->ToString()))) {
                                                                                                  ^
In file included from /root/.node-gyp/10.14.0/include/node/node.h:63:0,
                 from Release/obj.target/appmetrics/geni/appmetrics.cpp:21:
/root/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
make: *** [Makefile:282: Release/obj.target/appmetrics/geni/appmetrics.o] Error 1
make: Leaving directory '/tmp/node_modules/appmetrics-statsd/node_modules/appmetrics/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/appmetrics-statsd/node_modules/appmetrics
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appmetrics@3.1.3 install: `node extract_all_binaries.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appmetrics@3.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-30T17_32_29_732Z-debug.log
```

**Comment by mattcolegate** [comment]
Hi @DanailMinchev, Node 10 support was added in appmetrics@4.0.1 - can you try again with an updated package.json? You seem to be attempting to install appmetrics@3.1.3.

**Comment by DanailMinchev** [comment]
Hi @mattcolegate , thank you, that was the problem, it works now!

**Comment by gustavomassa** [comment]
The issues was related to npm cache, when I tried to update from 4.0.0 to 4.0.0.1, I had to clean the npm cache and delete the entire node modules folder to be able to compile the new version correctly.

**Comment by DanailMinchev** [comment]
@mattcolegate @tobespc It looks like it is failing on another dependency now - https://github.com/RuntimeTools/appmetrics-statsd/issues/11
just wanted to notify related issue, thanks
