### ISSUE TITLE
Cannot install appmetrics with Node.js v12 on MacOS

### ISSUE THREAD

**Issue by yuecchen** [RuntimeTools/appmetrics#572]
With Node.js v12, run `npm install appmetrics`, we got some error while compile:

```
Release/obj.target/appmetrics/geni/appmetrics.cpp:665:52: error: no matching
      member function for call to 'ToObject'
            Local<Value> gpfilename = grandparent->ToObject()->Get(Nan::...
                                      ~~~~~~~~~~~~~^~~~~~~~
/Users/yuecchen/.node-gyp/12.0.0/include/node/v8.h:2532:44: note: candidate
      function not viable: requires single argument 'context', but no arguments
      were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
```

and 

```
../src/plugins/node/prof/compat-inl.h:302:19: error: no member named
      'GetCpuProfiler' in 'v8::Isolate'
  return isolate->GetCpuProfiler()->StartProfiling(title, record_samples);
         ~~~~~~~  ^
../src/plugins/node/prof/compat-inl.h:312:19: error: no member named
      'GetCpuProfiler' in 'v8::Isolate'
  return isolate->GetCpuProfiler()->StopProfiling(title);
         ~~~~~~~  ^
```

here is the install log: 
[2018-11-28T14_57_12_372Z-debug.log](https://github.com/RuntimeTools/appmetrics/files/3114969/2018-11-28T14_57_12_372Z-debug.log)

**Comment by rwalle61** [comment]
@yuecchen thanks for opening the issue, I'm working on it now

**Comment by rwalle61** [comment]
### Update: https://github.com/RuntimeTools/appmetrics/pull/576 has been merged!

**Comment by rwalle61** [comment]
@yuecchen can you pull Appmetrics 5.0.0 and see if you can install on Node 12?

**Comment by rwalle61** [comment]
As you closed https://github.com/RuntimeTools/appmetrics/issues/573, I assume this is safe to close too

**Comment by n1th1l** [comment]
This is not working on v12.13, also tried on v12.6

**Comment by mattcolegate** [comment]
@n1th1l Our Travis test for Appmetrics 5.1.1 on Node 12.13 on MacOS passed cleanly: https://travis-ci.org/RuntimeTools/appmetrics/jobs/606748803?utm_medium=notification&utm_source=github_status
Can you provide some more detail on the problems you are seeing please?

**Comment by tmkasun** [comment]
I tried to install appmetrics on node v12.18.3 in mac catalina, It's not working. getting bunch of

```
error: no matching
      member function for call to 'ToObject'
```

errors

**Comment by mattcolegate** [comment]
@tmkasun Our latest Travis test for Appmetrics 5.1.1 on Node 12.18.4 failed in the test stage but did pass installation: https://travis-ci.org/github/RuntimeTools/appmetrics/jobs/733041231

Can you provide the entire log output for the installation attempt please?
